### ISSUE TITLE
Splitting flawfinder source code into spearate files

### ISSUE THREAD

**Issue by jhachenbergerSIT** [david-a-wheeler/flawfinder#14]
The `CONTRIBUTING.md` states:

> To make the program easy to install everywhere, the main executable is exactly one self-contained file.

This is definitely a valid argument. Still, I think you spent a lot of effort in making the installation as easy as possible using common tools like pip or apt. Additionally, 2k LoC are really not easy to parse (from a human perspective). Hence I would argue that it is already easy enough to install flawfinder in comparison to the readability of the source code. Thus, it might be more important to improve latter.

How do you think about this?

**Comment by david-a-wheeler** [comment]
In this particular case, I think "ease of installation" is more important than "use multiple files".  Not everyone uses pip. Indeed, some organizations aren't allowed unfettered Internet access, so they may not be able to use pip, and in that case bringing in a single file (after review) can be easier.

I think this is a specialized circumstance; usually I would also split this up into multiple files.  But I'm willing to do unusual things so that more users can use the software.

Thanks for the comment!
